// <auto-generated />
using System;
using BDSA2019.Lecture04;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BDSA2019.Lecture04.Migrations
{
    [DbContext(typeof(SuperheroContext))]
    [Migration("20190920091938_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-rc1.19456.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BDSA2019.Lecture04.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Metropolis"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gotham City"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Atlantis"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Themyscira"
                        },
                        new
                        {
                            Id = 5,
                            Name = "New York City"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Central City"
                        });
                });

            modelBuilder.Entity("BDSA2019.Lecture04.Superhero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlterEgo")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("FirstAppearance")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Superheroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlterEgo = "Aquaman",
                            CityId = 1,
                            FirstAppearance = 1941,
                            Gender = 1,
                            Name = "Arthur Curry",
                            Occupation = "King of Atlantis"
                        },
                        new
                        {
                            Id = 2,
                            AlterEgo = "Superman",
                            CityId = 1,
                            FirstAppearance = 1938,
                            Gender = 1,
                            Name = "Clark Kent",
                            Occupation = "Reporter"
                        },
                        new
                        {
                            Id = 3,
                            AlterEgo = "Batman",
                            CityId = 2,
                            FirstAppearance = 1939,
                            Gender = 1,
                            Name = "Bruce Wayne",
                            Occupation = "CEO of Wayne Enterprises"
                        },
                        new
                        {
                            Id = 4,
                            AlterEgo = "Wonder Woman",
                            CityId = 4,
                            FirstAppearance = 1941,
                            Gender = 0,
                            Name = "Diana",
                            Occupation = "Amazon Princess"
                        },
                        new
                        {
                            Id = 5,
                            AlterEgo = "Green Lantern",
                            CityId = 5,
                            FirstAppearance = 1940,
                            Gender = 1,
                            Name = "Hal Jordan",
                            Occupation = "Test pilot"
                        },
                        new
                        {
                            Id = 6,
                            AlterEgo = "The Flash",
                            CityId = 6,
                            FirstAppearance = 1940,
                            Gender = 1,
                            Name = "Barry Allen",
                            Occupation = "Forensic scientist"
                        },
                        new
                        {
                            Id = 7,
                            AlterEgo = "Catwoman",
                            CityId = 2,
                            FirstAppearance = 1940,
                            Gender = 0,
                            Name = "Selina Kyle",
                            Occupation = "Thief"
                        },
                        new
                        {
                            Id = 8,
                            AlterEgo = "Batwoman",
                            CityId = 2,
                            FirstAppearance = 1956,
                            Gender = 0,
                            Name = "Kate Kane",
                            Occupation = "Thief"
                        },
                        new
                        {
                            Id = 9,
                            AlterEgo = "Supergirl",
                            CityId = 5,
                            FirstAppearance = 1959,
                            Gender = 0,
                            Name = "Kara Zor-El",
                            Occupation = "Actress"
                        });
                });

            modelBuilder.Entity("BDSA2019.Lecture04.Superhero", b =>
                {
                    b.HasOne("BDSA2019.Lecture04.City", "City")
                        .WithMany("Superheroes")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
